version: "2"

run:
  timeout: 5m
  relative-path-mode: gomod
  modules-download-mode: readonly
  allow-parallel-runners: true
  tests: true
  build-tags: []
  go: "1.25"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: false
  sort-results: false

linters:
  enable-all: true
  disable:
    - wsl
    - nlreturn
    - gocognit
    - cyclop
    - exhaustruct
    - nilnil
    - lll
    - funlen
    - mnd
    - depguard
    - tagalign

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/zercle/template-go-echo
  govet:
    enable-all: true
  staticcheck:
    checks: ["all"]
  errcheck:
    check-type-assertions: true
    check-blank: false
  misspell:
    locale: US

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
