version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: template-go-echo-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  # API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: template-go-echo-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      SERVER_PORT: 3000
      SERVER_HOST: 0.0.0.0
      DATABASE_DRIVER: mysql
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: app_user
      DATABASE_PASSWORD: app_password
      DATABASE_NAME: app_db
      DATABASE_SSL_MODE: disable
      AUTH_JWT_SECRET: dev-secret-key-change-in-production
      AUTH_TOKEN_TTL: 3600
      LOGGING_LEVEL: info
      LOGGING_JSON: true
    ports:
      - "3000:3000"
    networks:
      - app_network
    restart: on-failure

  # Optional: phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: template-go-echo-phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    networks:
      - app_network
    restart: on-failure

volumes:
  db_data:
    driver: local

networks:
  app_network:
    driver: bridge
