// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

// User session tokens
type UserSessions struct {
	// UUIDv7 unique identifier
	ID string `db:"id" json:"id"`
	// Foreign key to users
	UserID string `db:"user_id" json:"user_id"`
	// Hashed refresh token
	RefreshTokenHash string `db:"refresh_token_hash" json:"refresh_token_hash"`
	// Client IP address
	IpAddress sql.NullString `db:"ip_address" json:"ip_address"`
	// Client user agent
	UserAgent sql.NullString `db:"user_agent" json:"user_agent"`
	// Token expiration time
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
	// Creation timestamp
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
}

// User accounts
type Users struct {
	// UUIDv7 unique identifier
	ID string `db:"id" json:"id"`
	// User email address
	Email string `db:"email" json:"email"`
	// User full name
	Name string `db:"name" json:"name"`
	// Bcrypt hashed password
	PasswordHash string `db:"password_hash" json:"password_hash"`
	// Account status
	IsActive sql.NullBool `db:"is_active" json:"is_active"`
	// Creation timestamp
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	// Last update timestamp
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
	// Soft delete timestamp
	DeletedAt sql.NullTime `db:"deleted_at" json:"deleted_at"`
}
