// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	// SQL queries for user session domain
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	// SQL queries for user domain
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteSession(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	GetSessionByID(ctx context.Context, id string) (UserSessions, error)
	GetSessionByTokenHash(ctx context.Context, refreshTokenHash string) (UserSessions, error)
	GetSessionByUserID(ctx context.Context, userID string) ([]UserSessions, error)
	GetUserByEmail(ctx context.Context, email string) (Users, error)
	GetUserByID(ctx context.Context, id string) (Users, error)
	GetUserCount(ctx context.Context) (int64, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]Users, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
