// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

// Users domain table
type User struct {
	// UUID v4 identifier
	ID string `db:"id" json:"id"`
	// User full name
	Name string `db:"name" json:"name"`
	// User email address
	Email string `db:"email" json:"email"`
	// Record creation timestamp
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	// Record update timestamp
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
}
